(() => {"use strict";
const API="/api/admin/evidence-drafts"; const EXPORT="data/v2/exports/prachinlife_places_v2.json"; let currentStatus="pending_review"; let placesById=new Map();
const $=id=>document.getElementById(id); const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const label={canonical_name:"ชื่อ",province:"จังหวัด",district:"อำเภอ",subdistrict:"ตำบล",area:"พื้นที่",address_text:"ที่อยู่",location:"พิกัด",categories:"หมวด",phone:"โทรศัพท์",website:"เว็บไซต์",opening_hours:"เวลาเปิด",real_image:"รูปจริง",description:"รายละเอียด"};
const kindLabel={added:"เพิ่มใหม่",changed:"แก้ไข",removed:"เอาออก"};
function value(v){if(v==null||v==="")return "—";if(typeof v==="object")return JSON.stringify(v);return String(v);}
function title(item){const changes=item.payload?.changes||[];const named=changes.find(x=>x.field_name==="canonical_name");return named?.value||placesById.get(item.target_place_id)?.name||item.payload?.current_place_name||item.target_place_id||"สถานที่ใหม่";}
function seedPlace(item){const seed=item.payload?.review_context?.seed_snapshot;if(!seed||typeof seed!=="object")return {};return {...seed};}
function basePlace(item){if(item.target_place_id)return placesById.get(item.target_place_id)||{};return seedPlace(item);}
function operatorChanges(item){const explicit=item.payload?.review_context?.operator_changes;return Array.isArray(explicit)?explicit:(item.target_place_id?(item.payload?.changes||[]):[]);}
function hasLegacySeed(item){return item.operation==="create_place_candidate"&&item.payload?.review_context?.baseline_kind==="legacy_seed"&&Object.keys(seedPlace(item)).length>0;}
function previewHtml(item){const api=window.PrachinLifeAdminPreview;if(!api)return '<p class="admin-muted">Preview renderer ไม่พร้อม</p>';const before=basePlace(item);const after=api.applyChanges(before,item.payload?.changes||[]);if(item.payload?.source?.source_url&&!after.source_url)after.source_url=item.payload.source.source_url;const left=(item.target_place_id||hasLegacySeed(item))?api.renderCard(before,{caption:hasLegacySeed(item)?"ข้อมูลตั้งต้น":"ก่อนปรับปรุง"}):'<div class="admin-preview-caption">ก่อนปรับปรุง</div><div class="admin-preview-empty">สถานที่ใหม่ — ยังไม่มีข้อมูลตั้งต้น</div>';return `<div class="admin-before-after-preview"><div class="admin-preview-column">${left}</div><div class="admin-preview-column is-after">${api.renderCard(after,{caption:"หลังปรับปรุง"})}</div></div>`;}
function imageDiffValue(v,caption){const src=String(v||"").trim();if(!src)return `<div class="admin-image-diff-empty">${esc(caption)}: ไม่มีรูปจริง / ใช้ภาพ Master</div>`;return `<figure class="admin-image-diff-figure"><figcaption>${esc(caption)}</figcaption><img src="${esc(src)}" alt="${esc(caption)}" loading="lazy"><small>${esc(src)}</small></figure>`;}
function renderDiffRow(d){if(d.field_name==="real_image")return `<div class="admin-diff-row admin-diff-image-row is-${esc(d.kind||"changed")}"><span class="admin-diff-kind">${esc(kindLabel[d.kind]||d.kind||"แก้ไข")}</span><b>${esc(label[d.field_name]||d.field_name)}</b><div class="admin-image-diff-pair">${imageDiffValue(d.before,"รูปก่อนหน้า")}<span aria-hidden="true">→</span>${imageDiffValue(d.after,"รูปที่เสนอ")}</div></div>`;return `<div class="admin-diff-row is-${esc(d.kind||"changed")}"><span class="admin-diff-kind">${esc(kindLabel[d.kind]||d.kind||"แก้ไข")}</span><b>${esc(label[d.field_name]||d.field_name)}</b><span class="admin-diff-before">${esc(value(d.before))}</span><span aria-hidden="true">→</span><strong>${esc(value(d.after))}</strong></div>`;}
function seedSummaryHtml(item){if(!hasLegacySeed(item))return "";const seed=seedPlace(item);const parts=[["ชื่อ",seed.name],["จังหวัด",seed.province],["อำเภอ",seed.district],["ตำบล",seed.subdistrict],["ที่อยู่",seed.address],["หมวด",seed.categories],["พิกัด",seed.latitude!=null&&seed.longitude!=null?`${seed.latitude}, ${seed.longitude}`:""]].filter(x=>x[1]!==""&&x[1]!=null&&(!Array.isArray(x[1])||x[1].length));return `<details class="admin-seed-summary"><summary>ข้อมูลตั้งต้นที่จะสร้างใน V2 (${parts.length} รายการ)</summary><div class="admin-seed-grid">${parts.map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(value(v))}</strong></div>`).join("")}</div></details>`;}
function diffHtml(item){const operator=operatorChanges(item);if(hasLegacySeed(item)){const seed=seedPlace(item);const enriched=operator.map(c=>{let before="";switch(c.field_name){case"canonical_name":before=seed.name;break;case"address_text":before=seed.address;break;case"location":before=(seed.latitude!=null&&seed.longitude!=null)?{latitude:seed.latitude,longitude:seed.longitude}:null;break;case"real_image":before=seed.real_image;break;default:before=seed[c.field_name];}const kind=(before==null||before===""||(Array.isArray(before)&&!before.length))?"added":"changed";return {field_name:c.field_name,kind,before,after:c.value};});return `${seedSummaryHtml(item)}<section class="admin-change-summary is-operator"><div class="admin-change-summary-head"><strong>สิ่งที่ Admin เปลี่ยน / เติมในรอบนี้</strong><span>${enriched.length} รายการที่ต้องตรวจ</span></div><div class="admin-diff-list">${enriched.length?enriched.map(renderDiffRow).join(""):'<p class="admin-muted">ไม่มีค่าที่ต่างจากข้อมูลตั้งต้น</p>'}</div></section>`;}const diff=item.version_diff||[];if((item.versions_total||1)<=1){const first=item.payload?.changes||[];return `<section class="admin-change-summary is-first"><div class="admin-change-summary-head"><strong>${item.operation==="create_place_candidate"?"ข้อมูลที่จะสร้างใน V2":"สิ่งที่เปลี่ยน"}</strong><span>ตรวจข้อมูลที่เสนอด้านล่าง</span></div><div class="admin-diff-list">${first.map(c=>renderDiffRow({field_name:c.field_name,kind:"added",before:null,after:c.value})).join("")}</div></section>`;}if(!diff.length)return '<div class="admin-change-summary"><strong>เวอร์ชันล่าสุดไม่มีค่าต่างจากเวอร์ชันก่อน</strong></div>';return `<section class="admin-change-summary"><div class="admin-change-summary-head"><strong>สิ่งที่เปลี่ยนจากเวอร์ชันก่อนหน้า</strong><span>v${esc(item.draft_version-1)} → v${esc(item.draft_version)}</span></div><div class="admin-diff-list">${diff.map(renderDiffRow).join("")}</div></section>`;}
function historyHtml(item){const history=item.version_history||[];if(history.length<=1)return "";return `<details class="admin-version-history"><summary>ประวัติ Draft ${esc(history.length)} เวอร์ชัน</summary><div>${history.slice().reverse().map(v=>`<div class="admin-version-row ${v.is_latest?'is-latest':''}"><span>v${esc(v.version)} ${v.is_latest?'(ล่าสุด)':''}</span><span>${esc(v.status)}</span><span>${esc(v.changes_count)} field</span><small>${esc(v.created_at)}</small></div>`).join("")}</div></details>`;}
function communityReport(item){const m=item.payload?.contribution_metadata||{};return m.origin==="public_suggest_edit"&&m.trust_tier==="untrusted_community_report";}

function process3Links(item){
  if(!item||item.status!=="approved"||communityReport(item)||item.operation!=="update_place_candidate") return "";
  const srcName=item.source_name||item.payload?.source?.source_name||"";
  const srcUrl=item.source_url||item.payload?.source?.source_url||"";
  const observed=item.reviewed_at||item.updated_at||item.created_at||"";
  const note=item.review_note||"";
  const allowed=(item.payload?.changes||[]).filter(c=>c&&(c.field_name==="phone"||c.field_name==="website")&&String(c.value??"").trim());
  if(!allowed.length) return "";
  const links=allowed.map(c=>{
    const q=new URLSearchParams({
      from_approved_draft:"1",draft_id:String(item.draft_id||""),place_id:String(item.target_place_id||""),
      field:String(c.field_name),value:String(c.value),source_name:String(srcName),source_url:String(srcUrl),
      observed_at:String(observed),note:String(note)
    });
    return `<a class="button" data-process3-link href="admin-verified-update.html?${q.toString()}">ไป Process 3: ${esc(label[c.field_name]||c.field_name)}</a>`;
  }).join("");
  return `<div class="admin-review-gate"><strong>พร้อมเข้าสู่ Process 3</strong><p class="admin-muted">Draft นี้อนุมัติแล้ว แต่ยังไม่แก้ DB/Production จนกว่า Owner/Admin จะ Dry-run และยืนยัน Publish</p><div class="admin-actions">${links}</div></div>`;
}

function card(item){const changes=hasLegacySeed(item)?operatorChanges(item):(item.payload?.changes||[]);const seed=seedPlace(item);const oldFor=c=>{if(!hasLegacySeed(item))return c.old_value??c.previous_value;if(c.field_name==="canonical_name")return seed.name;if(c.field_name==="address_text")return seed.address;if(c.field_name==="location")return (seed.latitude!=null&&seed.longitude!=null)?{latitude:seed.latitude,longitude:seed.longitude}:null;if(c.field_name==="real_image")return seed.real_image;return seed[c.field_name];};const rows=changes.map(c=>`<tr><th>${esc(label[c.field_name]||c.field_name)}</th><td>${esc(value(oldFor(c)))}</td><td>${esc(value(c.value))}</td></tr>`).join("");const pending=item.status==="pending_review";const versionBadge=(item.versions_total||1)>1?`<span class="admin-version-badge">v${esc(item.draft_version)} · ${esc(item.versions_total)} เวอร์ชัน</span>`:"";
return `<article class="admin-review-card" data-draft-id="${esc(item.draft_id)}"><div class="admin-review-head"><div><span class="admin-mode-badge">${esc(item.operation)}</span>${versionBadge}<h3>${esc(title(item))}</h3><p class="admin-muted">Draft ${esc(item.draft_id)} • ${esc(item.created_at)}</p></div><strong>${esc(item.status)}</strong></div>${diffHtml(item)}${previewHtml(item)}${historyHtml(item)}<div class="admin-review-source"><b>หลักฐาน:</b> ${esc(item.source_name)} · <a href="${esc(item.source_url)}" target="_blank" rel="noopener noreferrer">เปิดแหล่งข้อมูล</a></div><div class="admin-review-table-wrap"><table class="admin-review-table"><thead><tr><th>ข้อมูล</th><th>ค่าเดิม</th><th>ค่าที่เสนอ</th></tr></thead><tbody>${rows||'<tr><td colspan="3">ไม่มีรายการเปลี่ยนแปลง</td></tr>'}</tbody></table></div>${pending?`<div class="admin-review-gate">${communityReport(item)?"COMMUNITY REPORT • HOLD — ห้ามอนุมัติโดยตรง ต้องตรวจจากหลักฐานอิสระแล้วสร้าง Operator Evidence Draft ใหม่":"ตรวจ Diff, Card ก่อน / หลัง และหลักฐานก่อนตัดสินใจ"}</div><label class="admin-review-note"><span>หมายเหตุผู้ตรวจ</span><textarea rows="2" data-review-note placeholder="เหตุผลหรือหมายเหตุ (ถ้ามี)"></textarea></label><div class="admin-actions">${communityReport(item)?"":`<button data-review-decision="approved">✓ อนุมัติเวอร์ชันล่าสุด</button>`}<button class="danger" data-review-decision="rejected">✕ ปฏิเสธ</button></div>`:`<p class="admin-muted">หมายเหตุ: ${esc(item.review_note||"—")} ${item.reviewed_at?`• ${esc(item.reviewed_at)}`:""}</p>${process3Links(item)}`}</article>`;}
async function loadPlaces(){try{const r=await fetch(EXPORT,{cache:"no-store"});const d=await r.json();placesById=new Map((d.places||[]).map(p=>[String(p.id),p]));}catch{placesById=new Map();}}
async function load(status=currentStatus){currentStatus=status;$("reviewStatus").textContent="กำลังโหลด...";try{const r=await fetch(`${API}?status=${encodeURIComponent(status)}`,{cache:"no-store"});const data=await r.json();if(!r.ok)throw new Error(data.error||"โหลดไม่สำเร็จ");$("reviewCount").textContent=`${data.count} สถานที่`;$("reviewList").innerHTML=data.items.length?data.items.map(card).join(""):'<div class="empty-state"><h3>ไม่มีรายการ</h3></div>';$("reviewStatus").textContent="รวม Draft ร้านเดียวกันเป็นเวอร์ชัน • ตรวจ Diff และ Preview ก่อนตัดสินใจ • Canonical DB ยังไม่เปลี่ยน";bind();}catch(e){$("reviewStatus").textContent=e.message;}}
function bind(){document.querySelectorAll("[data-review-decision]").forEach(btn=>btn.addEventListener("click",async()=>{const cardNode=btn.closest("[data-draft-id]");const id=cardNode.dataset.draftId;const note=cardNode.querySelector("[data-review-note]")?.value||"";btn.disabled=true;try{const r=await fetch(`${API}/${encodeURIComponent(id)}/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision:btn.dataset.reviewDecision,note})});const data=await r.json();if(!r.ok)throw new Error(data.error||"บันทึกผล Review ไม่สำเร็จ");await load(currentStatus);}catch(e){$("reviewStatus").textContent=e.message;btn.disabled=false;}}));}
document.querySelectorAll("[data-review-filter]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-review-filter]").forEach(x=>x.classList.add("secondary"));btn.classList.remove("secondary");load(btn.dataset.reviewFilter);}));
(async()=>{await loadPlaces();await load();})();
})();
